Repository FraunhoferISST/Innamark, pull requests merged in 2024-06, with the labels that each got.

#72 fix(samples): update outdated JS examples
  samples/js_modules/js_modules_minimal_example.js
  samples/plain_js/plain_js_minimal_example.html
Labels: bug, documentation, component: watermarker

#75 feat(watermarker): add support for TrendmarkBuilder to getMinimumInsertPositions
  watermarker/src/commonMain/kotlin/fileWatermarker/TextWatermarker.kt
Labels: feature, component: watermarker

#82 docs: add initial documentation structure
  CONTRIBUTING.md
  README.md
  docs/docs/01-introduction.mdx
  docs/docs/02-getting-started.mdx
  docs/docs/03-usage/10-watermarker/01-installation.md
  docs/docs/03-usage/10-watermarker/index.mdx
  docs/docs/03-usage/10-watermarker/java.md
  docs/docs/03-usage/10-watermarker/javascript.md
  docs/docs/03-usage/11-cli/01-installation.md
  docs/docs/03-usage/11-cli/commands.md
  docs/docs/03-usage/11-cli/index.md
  docs/docs/03-usage/12-webinterface/01-installation.md
  docs/docs/03-usage/12-webinterface/index.md
  docs/docs/03-usage/index.mdx
  docs/docs/04-development/10-watermarker/index.mdx
  docs/docs/04-development/10-watermarker/trendmark.md
  docs/docs/04-development/11-cli/index.md
  docs/docs/04-development/12-webinterface/index.md
  docs/docs/04-development/99-contributing.md
  docs/docs/04-development/index.mdx
  docs/docs/patent-hint.mdx
  docs/docusaurus.config.js
Labels: documentation

#89 style(docs): add TREND logo
  NOTICE.md
  docs/docusaurus.config.js
  docs/static/img/branding/favicon.ico
  docs/static/img/branding/icon/black/trend_icon_b.png
  docs/static/img/branding/icon/black/trend_icon_b.svg
  docs/static/img/branding/icon/white/trend_icon_w.png
  docs/static/img/branding/icon/white/trend_icon_w.svg
  docs/static/img/branding/logo-sub/black/trend_logo-sub_b.png
  docs/static/img/branding/logo-sub/black/trend_logo-sub_b.svg
  docs/static/img/branding/logo-sub/white/trend_logo-sub_w.png
  docs/static/img/branding/logo-sub/white/trend_logo-sub_w.svg
  docs/static/img/branding/logo/black/trend_logo_b.png
  docs/static/img/branding/logo/black/trend_logo_b.svg
  docs/static/img/branding/logo/white/trend_logo_w.png
  docs/static/img/branding/logo/white/trend_logo_w.svg
Labels: documentation
